#version: "3.8"
#services:
#  app :
#    build: ./app/back
#    restart: always
#    ports:
#      - "5050:5050"
#    depends_on:
#      - db
#  db:
#    build: ./database/
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_DB=database

version: "3"
services:
  app :
    build: ./app/back
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - db
  sonarqube:
    build: ./sonarqube
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/database
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: postgres
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  sonarscanner:
    image: sonarsource/sonar-scanner-cli:latest
    volumes:
      - ./app/back:/usr/src
    command: sonar-scanner -Dsonar.projectBaseDir=/usr/src
    depends_on:
      - sonarqube
  db:
    build: ./database/
    restart: always
    ports:
      - "5432:5432"
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
